### ISSUE TITLE
Error occurs when User-Agent header is missing

### ISSUE THREAD

**Issue by koseki** [WOVNio/WOVN.php#183]
https://github.com/WOVNio/WOVN.php/blob/80f28c7286d53cc06d38d6c9c086a771c54bb26b/src/wovnio/wovnphp/Headers.php#L396-L400

The above code seems to be causing errors.

```
Undefined index: HTTP_USER_AGENT in /.../WOVN.php/src/wovnio/wovnphp/Headers.php:397
```

**Comment by bstewart00** [comment]
Fixed in https://github.com/WOVNio/WOVN.php/releases/tag/1.14.4
